ALTER SEQUENCE classroom_id_seq INCREMENT BY 50;
ALTER SEQUENCE course_id_seq INCREMENT BY 50;
ALTER SEQUENCE faculty_id_seq INCREMENT BY 50;
ALTER SEQUENCE groups_id_seq INCREMENT BY 50;
ALTER SEQUENCE teacher_id_seq INCREMENT BY 50;
ALTER SEQUENCE student_id_seq INCREMENT BY 50;
ALTER SEQUENCE schedule_id_seq INCREMENT BY 50;
